// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrjzPvRNZzYnuamkeVQvonVUWq4aUl03k',
    appId: '1:489417437365:web:3eb58df521a076eda04efc',
    messagingSenderId: '489417437365',
    projectId: 'cmsc23-b7l-group2-health-app',
    authDomain: 'cmsc23-b7l-group2-health-app.firebaseapp.com',
    storageBucket: 'cmsc23-b7l-group2-health-app.appspot.com',
    measurementId: 'G-DHK1M6EKLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1kPR85AgB2Ik16linwUlELtzGh2_Bvk',
    appId: '1:489417437365:android:ed4dab9bf5803b57a04efc',
    messagingSenderId: '489417437365',
    projectId: 'cmsc23-b7l-group2-health-app',
    storageBucket: 'cmsc23-b7l-group2-health-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOl1OYmequTuT8M1-NrHnBIx7OcOaUYr4',
    appId: '1:489417437365:ios:cb09ada4146712d0a04efc',
    messagingSenderId: '489417437365',
    projectId: 'cmsc23-b7l-group2-health-app',
    storageBucket: 'cmsc23-b7l-group2-health-app.appspot.com',
    iosClientId:
        '489417437365-83n73f38ambc43vbbroglacblqsefth7.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOl1OYmequTuT8M1-NrHnBIx7OcOaUYr4',
    appId: '1:489417437365:ios:cb09ada4146712d0a04efc',
    messagingSenderId: '489417437365',
    projectId: 'cmsc23-b7l-group2-health-app',
    storageBucket: 'cmsc23-b7l-group2-health-app.appspot.com',
    iosClientId:
        '489417437365-83n73f38ambc43vbbroglacblqsefth7.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitoringApp',
  );
}
